<?php

$tourAuthUser = auth()->user();
$tourSteps = collect([
    [
        'key' => 'products',
        'title' => 'Create products and materials',
        'section' => 'Control Setup',
        'purpose' => 'Every downstream workflow depends on valid products, SKUs, and materials.',
        'action' => 'Before adding a product, set up Packaging Types and Tax / VAT Classes. Then create the SKU with its name, price, packaging, and tax linkage.',
        'path' => route('admin.products.index'),
        'selector' => '[data-tour="products-primary-action"]',
        'permission' => 'control.products',
    ],
    [
        'key' => 'products-form',
        'title' => 'Fill the product form',
        'section' => 'Control Setup',
        'purpose' => 'A usable product record needs more than just a name. Sales, inventory, VAT, and packaging all read from this setup.',
        'action' => 'If Packaging Types and Tax / VAT Classes are already created, fill Product Name, SKU, base price, packaging type, and tax class first. Then add size, volume, image, and description.',
        'path' => route('admin.products.create'),
        'selector' => '[data-tour="product-form-basics"]',
        'spotlight' => false,
        'permission' => 'control.products',
    ],
    [
        'key' => 'products-save',
        'title' => 'Save and publish the SKU',
        'section' => 'Control Setup',
        'purpose' => 'Saving the product makes it available to pricing, stock, BOM, and order workflows.',
        'action' => 'After checking the required fields and keeping the SKU active, use Save Product to add it to the catalog.',
        'path' => route('admin.products.create'),
        'selector' => '[data-tour="product-form-submit"]',
        'permission' => 'control.products',
    ],
    [
        'key' => 'agents',
        'title' => 'Register agents and customers',
        'section' => 'Control Setup',
        'purpose' => 'Sales orders, credit checks, pricing, and commissions all depend on the agent master.',
        'action' => 'Create agents, then maintain their price lists, credit terms, and commission rules.',
        'path' => route('admin.agents.index'),
        'selector' => '[data-tour="agents-primary-action"]',
        'permission' => 'control.agents',
    ],
    [
        'key' => 'suppliers',
        'title' => 'Maintain suppliers',
        'section' => 'Control Setup',
        'purpose' => 'Procurement starts from the supplier master.',
        'action' => 'Add supplier contacts, then use them when raising purchase orders and purchase bills.',
        'path' => route('admin.suppliers.index'),
        'selector' => '[data-tour="suppliers-primary-action"]',
        'permission' => 'control.suppliers',
    ],
    [
        'key' => 'warehouses',
        'title' => 'Set up warehouses',
        'section' => 'Control Setup',
        'purpose' => 'Stock visibility depends on warehouse structure and locations.',
        'action' => 'Create warehouses, depots, and storage locations before posting receipts, transfers, or deliveries.',
        'path' => route('admin.warehouses.index'),
        'selector' => '[data-tour="warehouses-primary-action"]',
        'permission' => 'control.warehouses',
    ],
    [
        'key' => 'purchase-orders',
        'title' => 'Raise purchase orders',
        'section' => 'Procurement',
        'purpose' => 'This starts the inbound material cycle from supplier to inventory.',
        'action' => 'Create and approve purchase orders for raw materials and packaging items that need replenishment.',
        'path' => route('admin.purchase-orders.index'),
        'selector' => '[data-tour="purchase-orders-primary-action"]',
        'permission' => 'control.suppliers',
    ],
    [
        'key' => 'goods-receipts',
        'title' => 'Post goods receipts',
        'section' => 'Procurement',
        'purpose' => 'GRN posting moves received material into stock and links it to procurement.',
        'action' => 'Receive supplier deliveries, record quantities, and confirm which stock entered the warehouse.',
        'path' => route('admin.goods-receipts.index'),
        'selector' => '[data-tour="goods-receipts-primary-action"]',
        'permission' => 'inventory.manage',
    ],
    [
        'key' => 'boms',
        'title' => 'Define BOMs',
        'section' => 'Manufacturing',
        'purpose' => 'Bills of material define what production will consume.',
        'action' => 'Map each finished good to its raw materials and packaging quantities before production runs are created.',
        'path' => route('admin.boms.index'),
        'selector' => '[data-tour="boms-primary-action"]',
        'permission' => 'manufacturing.manage',
    ],
    [
        'key' => 'production',
        'title' => 'Run production orders',
        'section' => 'Manufacturing',
        'purpose' => 'Production converts material stock into finished goods with batch control.',
        'action' => 'Create production runs, issue materials, confirm stock, and track QC-ready finished output.',
        'path' => route('admin.production.index'),
        'selector' => '[data-tour="production-primary-action"]',
        'permission' => 'manufacturing.manage',
    ],
    [
        'key' => 'inventory',
        'title' => 'Review inventory position',
        'section' => 'Inventory',
        'purpose' => 'This shows what is available, reserved, and ready for fulfilment.',
        'action' => 'Use the inventory views to check stock health before promising deliveries or planning more production.',
        'path' => route('admin.inventory.index'),
        'selector' => '[data-tour="inventory-overview-header"]',
        'permission' => 'inventory.manage',
    ],
    [
        'key' => 'orders',
        'title' => 'Capture sales orders',
        'section' => 'Sales',
        'purpose' => 'Sales orders are the market-side trigger for reservation, delivery, invoicing, and commissions.',
        'action' => 'Enter orders, apply pricing, validate credit, and move demand into warehouse fulfilment.',
        'path' => route('admin.orders.index'),
        'selector' => '[data-tour="orders-primary-action"]',
        'permission' => 'sales.manage',
    ],
    [
        'key' => 'finance',
        'title' => 'Issue customer invoices',
        'section' => 'Accounting',
        'purpose' => 'Delivered quantities become invoices, VAT, and receivable entries here.',
        'action' => 'Review invoices, receipts, credit notes, and outstanding balances after delivery is confirmed.',
        'path' => route('admin.finance.index'),
        'selector' => '[data-tour="finance-overview-header"]',
        'permission' => 'accounting.manage',
    ],
    [
        'key' => 'reconciliation',
        'title' => 'Reconcile collections',
        'section' => 'Accounting',
        'purpose' => 'Cash collection is not complete until receipts are reconciled.',
        'action' => 'Use bank reconciliation to confirm collected receipts against the current finance period.',
        'path' => route('admin.finance.reconciliation'),
        'selector' => '[data-tour="reconciliation-overview-header"]',
        'permission' => 'accounting.manage',
    ],
    [
        'key' => 'reports',
        'title' => 'Close the cycle with reports',
        'section' => 'Reporting',
        'purpose' => 'Reports convert operations into management and financial truth.',
        'action' => 'Use the reports dashboard to review production, sales, finance, tax, and payroll summaries after transactions are complete.',
        'path' => route('admin.reports.dashboard'),
        'selector' => '[data-tour="reports-drilldown"]',
        'permission' => 'reports.view',
    ],
    [
        'key' => 'settings',
        'title' => 'Finish with system settings',
        'section' => 'System',
        'purpose' => 'Branding, mail, SMS, and backups keep the ERP production-ready.',
        'action' => 'Configure logo, colors, currency, SMTP, SMS, and backup controls for daily use.',
        'path' => route('admin.settings.index'),
        'selector' => '[data-tour="settings-brand-identity"]',
        'permission' => 'system.settings',
    ],
])->filter(function ($step) use ($tourAuthUser) {
    return empty($step['permission']) || \App\Helpers\Permission::can($tourAuthUser, $step['permission']);
})->map(function ($step) {
    unset($step['permission']);
    return $step;
})->values()->all();
