<?php

return [
    'inventory_gl_enabled' => env('ACCOUNTING_INVENTORY_GL', true),
    'cogs_recognition' => env('ACCOUNTING_COGS_RECOGNITION', 'invoice'),

    'accounts' => [
        'bank_default' => 'bank_brac',
        'bank_brac' => 'bank_brac',
        'bank_scb' => 'bank_scb',
        'trade_debtors' => 'trade_debtors',
        'agent_advances' => 'agent_advances',
        'input_vat' => 'input_vat',
        'raw_materials_inventory' => 'raw_materials',
        'raw_materials' => 'raw_materials',
        'packing_materials' => 'packing_materials',
        'finished_goods_inventory' => 'finished_goods',
        'finished_goods' => 'finished_goods',
        'work_in_progress' => 'wip',
        'wip' => 'wip',
        'trading_stock' => 'trading_stock',
        'grni_accrual' => 'grni_accrual',
        'trade_creditors' => 'trade_creditors',
        'supplier_payable' => 'supplier_payable',
        'vat_payable' => 'vat_payable',
        'commission_payable' => 'commission_payable',
        'product_sales' => 'product_sales',
        'sales_returns' => 'sales_returns',
        'other_income' => 'other_income',
        'cogs' => 'raw_material_consumption',
        'raw_material_consumption' => 'raw_material_consumption',
        'packing_material_consumption' => 'packing_material_consumption',
        'inventory_write_off' => 'inventory_write_off',
        'purchases' => 'purchases',
        'commission_expense' => 'commission_expense',
        'commission_payable' => 'commission_payable',
        'salaries_wages' => 'salaries_wages',
        'salary_payable' => 'salary_payable',
        'rent_payable' => 'rent_payable',
        'utility_payable' => 'utility_payable',
        'cash_in_hand' => 'cash_in_hand',
        'petty_cash' => 'petty_cash',
        'wht_receivable' => 'wht_receivable',
        'input_vat' => 'input_vat',
        'accounts_payable' => 'trade_creditors',
        'marketing_expense' => 'marketing_expense',
        'utilities_expense' => 'utilities_expense',
        'delivery_expense' => 'delivery_expense',
        'selling_distribution' => 'selling_distribution',
        'office_rent' => 'office_rent',
        'retained_earnings' => 'retained_earnings',
    ],
];
