<?php

return [
    'hub_title' => ['en' => 'ERP Academy', 'bn' => 'ERP একাডেমি'],
    'hub_subtitle' => [
        'en' => 'Structured courses for every Saf ERP module — learn step by step, practice in the system, and pass the quiz to complete each course.',
        'bn' => 'প্রতিটি Saf ERP মডিউলের জন্য কাঠামোবদ্ধ কোর্স — ধাপে ধাপে শিখুন, সিস্টেমে অনুশীলন করুন, কুইজ পাস করে কোর্স সম্পন্ন করুন।',
    ],
    'overview_badge' => ['en' => 'Learning Hub', 'bn' => 'শেখার কেন্দ্র'],
    'search_placeholder' => ['en' => 'Search courses…', 'bn' => 'কোর্স খুঁজুন…'],
    'role_filter' => ['en' => 'I work in', 'bn' => 'আমার কাজ'],
    'role_everyone' => ['en' => 'Everyone', 'bn' => 'সবাই'],
    'flow_title' => ['en' => 'Process flow', 'bn' => 'প্রক্রিয়ার ধাপ'],
    'steps_title' => ['en' => 'How to do it', 'bn' => 'কীভাবে করবেন'],
    'examples_title' => ['en' => 'Worked examples', 'bn' => 'কাজের উদাহরণ'],
    'tips_title' => ['en' => 'Pro tips', 'bn' => 'গুরুত্বপূর্ণ টিপস'],
    'open_screen' => ['en' => 'Open in ERP', 'bn' => 'ERP-তে খুলুন'],
    'full_manual' => ['en' => 'Full manual', 'bn' => 'সম্পূর্ণ ম্যানুয়াল'],
    'start_tour' => ['en' => 'System tour', 'bn' => 'সিস্টেম ট্যুর'],
    'print_guide' => ['en' => 'Print course', 'bn' => 'কোর্স প্রিন্ট'],
    'learning_hub' => ['en' => 'Learning Hub', 'bn' => 'শেখার কেন্দ্র'],
    'tab_guide' => ['en' => 'Guide', 'bn' => 'গাইড'],
    'tab_technical' => ['en' => 'Deep reference', 'bn' => 'বিস্তারিত রেফারেন্স'],
    'audience_label' => ['en' => 'Built for', 'bn' => 'যাদের জন্য'],
    'reports_title' => ['en' => 'Reports & exports', 'bn' => 'রিপোর্ট ও এক্সপোর্ট'],
    'glossary_title' => ['en' => 'Glossary', 'bn' => 'শব্দকোষ'],
    'faq_title' => ['en' => 'Common questions', 'bn' => 'সাধারণ প্রশ্ন'],
    'related_screens' => ['en' => 'Related ERP screens', 'bn' => 'সম্পর্কিত ERP স্ক্রিন'],
    'progress_label' => ['en' => 'Academy progress', 'bn' => 'একাডেমি অগ্রগতি'],
    'progress_of' => ['en' => 'courses completed', 'bn' => 'কোর্স সম্পন্ন'],
    'no_results' => ['en' => 'No courses match your search or role.', 'bn' => 'আপনার অনুসন্ধান বা রোলে কোনো কোর্স নেই।'],
    'viewed' => ['en' => 'Started', 'bn' => 'শুরু করেছেন'],
    'debit' => ['en' => 'Debit', 'bn' => 'ডেবিট'],
    'credit' => ['en' => 'Credit', 'bn' => 'ক্রেডিট'],
    'account' => ['en' => 'Account', 'bn' => 'অ্যাকাউন্ট'],
    'type' => ['en' => 'Type', 'bn' => 'ধরন'],
    'code' => ['en' => 'Code', 'bn' => 'কোড'],
    'courses_title' => ['en' => 'All courses', 'bn' => 'সব কোর্স'],
    'courses_count' => ['en' => 'courses', 'bn' => 'কোর্স'],
    'lessons_label' => ['en' => 'lessons', 'bn' => 'পাঠ'],
    'minutes_label' => ['en' => 'min', 'bn' => 'মিনিট'],
    'start_course' => ['en' => 'Start course', 'bn' => 'কোর্স শুরু'],
    'continue_course' => ['en' => 'Continue', 'bn' => 'চালিয়ে যান'],
    'review_course' => ['en' => 'Review', 'bn' => 'পুনরায় দেখুন'],
    'completed' => ['en' => 'Completed', 'bn' => 'সম্পন্ন'],
    'in_progress' => ['en' => 'In progress', 'bn' => 'চলমান'],
    'not_started' => ['en' => 'Not started', 'bn' => 'শুরু হয়নি'],
    'recommended_path' => ['en' => 'Recommended for your role', 'bn' => 'আপনার রোলের জন্য সুপারিশকৃত'],
    'path_hint' => ['en' => 'Follow this order for the fastest onboarding.', 'bn' => 'দ্রুত অনবোর্ডিংয়ের জন্য এই ক্রম অনুসরণ করুন।'],
    'continue_learning' => ['en' => 'Continue learning', 'bn' => 'শেখা চালিয়ে যান'],
    'back_catalog' => ['en' => 'All courses', 'bn' => 'সব কোর্স'],
    'lesson_of' => ['en' => 'Lesson', 'bn' => 'পাঠ'],
    'of' => ['en' => 'of', 'bn' => '/'],
    'prev_lesson' => ['en' => 'Previous', 'bn' => 'আগের'],
    'next_lesson' => ['en' => 'Next lesson', 'bn' => 'পরের পাঠ'],
    'complete_lesson' => ['en' => 'Mark complete & continue', 'bn' => 'সম্পন্ন ও এগিয়ে যান'],
    'go_to_quiz' => ['en' => 'Go to quiz', 'bn' => 'কুইজে যান'],
    'course_outline' => ['en' => 'Course outline', 'bn' => 'কোর্স রূপরেখা'],
    'what_you_learn' => ['en' => 'What you will learn', 'bn' => 'যা শিখবেন'],
    'quiz_title' => ['en' => 'Knowledge check', 'bn' => 'জ্ঞান যাচাই'],
    'quiz_intro' => [
        'en' => 'Answer all questions. You need %pass%% to pass and complete this course.',
        'bn' => 'সব প্রশ্নের উত্তর দিন। কোর্স সম্পন্ন করতে %pass%% প্রয়োজন।',
    ],
    'quiz_submit' => ['en' => 'Submit answers', 'bn' => 'উত্তর জমা দিন'],
    'quiz_retry' => ['en' => 'Try again', 'bn' => 'আবার চেষ্টা'],
    'quiz_passed' => ['en' => 'You passed!', 'bn' => 'আপনি পাস করেছেন!'],
    'quiz_failed' => ['en' => 'Not quite — review the lessons and try again.', 'bn' => 'এখনো নয় — পাঠ দেখে আবার চেষ্টা করুন।'],
    'quiz_score' => ['en' => 'Your score', 'bn' => 'আপনার স্কোর'],
    'quiz_correct' => ['en' => 'Correct', 'bn' => 'সঠিক'],
    'quiz_explanation' => ['en' => 'Why', 'bn' => 'কারণ'],
    'certificate_title' => ['en' => 'Course completed', 'bn' => 'কোর্স সম্পন্ন'],
    'certificate_body' => [
        'en' => 'You finished all lessons and passed the quiz. You can revisit anytime.',
        'bn' => 'সব পাঠ শেষ ও কুইজ পাস করেছেন। যেকোনো সময় আবার দেখতে পারেন।',
    ],
    'stat_completed' => ['en' => 'Completed', 'bn' => 'সম্পন্ন'],
    'stat_in_progress' => ['en' => 'In progress', 'bn' => 'চলমান'],
    'stat_avg_score' => ['en' => 'Avg quiz score', 'bn' => 'গড় কুইজ স্কোর'],
    'track_foundation' => ['en' => 'Foundation', 'bn' => 'ভিত্তি'],
    'track_operations' => ['en' => 'Operations', 'bn' => 'অপারেশন'],
    'track_commercial' => ['en' => 'Commercial', 'bn' => 'বাণিজ্য'],
    'track_finance' => ['en' => 'Finance', 'bn' => 'অর্থ'],
    'level_beginner' => ['en' => 'Beginner', 'bn' => 'প্রাথমিক'],
    'level_intermediate' => ['en' => 'Intermediate', 'bn' => 'মধ্যম'],
    'level_advanced' => ['en' => 'Advanced', 'bn' => 'উন্নত'],
    'has_quiz' => ['en' => 'Quiz included', 'bn' => 'কুইজ আছে'],
    'expert_reference' => ['en' => 'Expert reference', 'bn' => 'বিশেষজ্ঞ রেফারেন্স'],
    'open_live_screen' => ['en' => 'Open this screen in ERP →', 'bn' => 'ERP-তে এই স্ক্রিন খুলুন →'],
    'field_required' => ['en' => 'Required', 'bn' => 'আবশ্যক'],
    'status_col' => ['en' => 'Status', 'bn' => 'স্ট্যাটাস'],
    'meaning_col' => ['en' => 'Meaning', 'bn' => 'অর্থ'],
    'screen_preview' => ['en' => 'Screen preview', 'bn' => 'স্ক্রিন প্রিভিউ'],
    'glossary_intro' => [
        'en' => 'Technical terms used in this course and in Saf ERP. Use search to find a word quickly.',
        'bn' => 'এই কোর্স ও Saf ERP-তে ব্যবহৃত প্রযুক্তিগত শব্দ। দ্রুত খুঁজতে সার্চ ব্যবহার করুন।',
    ],
    'glossary_search' => ['en' => 'Search terms…', 'bn' => 'শব্দ খুঁজুন…'],
    'glossary_empty' => ['en' => 'No terms match your search.', 'bn' => 'আপনার অনুসন্ধানে কোনো শব্দ নেই।'],
    'pipeline_title' => ['en' => 'Process at a glance', 'bn' => 'এক নজরে প্রক্রিয়া'],
    'walkthrough' => ['en' => 'Step-by-step walkthrough', 'bn' => 'ধাপে ধাপে গাইড'],
];
